import React from "react";
import SyntaxHighlighter from "react-syntax-highlighter";
import { atomOneDark } from "react-syntax-highlighter/dist/esm/styles/hljs";
import { theme } from "../../../theme";

const CodeBlock = ({ children, language = "javascript" }) => {
  // These styles are applied directly to the <pre> tag generated by SyntaxHighlighter.
  const customStyle = {
    padding: theme.spacing.lg,
    borderRadius: theme.borderRadius.xl,
    fontSize: theme.typography.fontSize.sm,
    lineHeight: theme.typography.lineHeight.relaxed,
    margin: 0,
  };

  return (
    <SyntaxHighlighter
      language={language}
      style={atomOneDark}
      customStyle={customStyle}
      showLineNumbers={false}
    >
      {String(children).trim()}
    </SyntaxHighlighter>
  );
};

export default CodeBlock;
